open Asttypes
open Parsetree

(** [compare_core_type ty] is an expression of type [ty -> ty -> int] *)
val compare_core_type : core_type -> expression

(** [equal_core_type ty] is an expression of type [ty -> ty -> bool], using the comparison
    function generated by [compare_core_type] *)
val equal_core_type : core_type -> expression

val str_type_decl
  :  loc:Location.t
  -> path:string
  -> rec_flag * type_declaration list
  -> structure

val sig_type_decl
  :  loc:Location.t
  -> path:string
  -> rec_flag * type_declaration list
  -> signature
